version: '3'
services:
  database:
    image: mysql:8
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_application
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
